language: go
dist: focal
jobs:
  include:
    - stage: test
      name: "Go 1.14"
      go:
        - 1.14.x
      install: skip
      script:
        - |
        make checkfmt
        make test
    - stage: test
      name: "Go 1.15"
      go:
        - 1.15.x
      install: skip
      script:
        - |
        make checkfmt
        make coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
